# layout configuration
layouts:
    - tall
    - fullscreen
    # - tall-right
    - wide
    # - two-pane
    # - 3column-left
    # - middle-wide
    # - 3column-right
    # - 4column-left
    # - 4column-right
    # - column
    # - row
    # - floating
    # - widescreen-tall
    # - widescreen-tall-right
    # - bsp

enables-layout-hud: true
enables-layout-hud-on-space-change: false
restore-layouts-on-launch: true

# general configuration
ignore-menu-bar: false
new-windows-to-main: false

# key bindings and modifications
mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

focus-screen-cw:
    - option
    - shift
    - k

focus-screen-ccw:
    - option
    - shift
    - j

# mouse configuration
mouse-follows-focus: false
focus-follows-mouse: false
mouse-swaps-windows: false
mouse-resizes-windows: false

# window management configuration
window-minimum-height: 0
window-minimum-width: 0
window-margins: true
window-margin-size: 60
smart-window-margins: false
window-resize-step: 1

# floating apps
float-small-windows: true
floating: ["com.cisco.anyconnect.gui", "com.microsoft.rdc.macos", "com.apple.systempreferences", "com.apple.FontBook", "com.hicknhack.macpass.kdbx"]
