palette:

  # tomorrow night color scheme
  # yellow: '#f0c674'           # yellow
  # green: '#b5bd68'            # green
  # magenta: '#c9b4cf'          # magenta
  # darkblue: '#41728e'         # dark blue
  # brightblue: '#88aabb'       # bright blue
  # orange: '#dd9955'           # orange
  # violet: '#b294bb'           # violet
  # red: '#cc6666'              # red
  # grey: '#5a5a5a'             # grey
  # cyan: '#8abeb7'             # cyan

  # rose pine color scheme
  red: '#b4637a'              # love
  yellow: '#ea9d34'           # gold
  pink: '#d7827e'             # rose
  blue: '#286983'             # pine
  cyan: '#56949f'             # foam
  violet: '#575279'           # text
  base: '#faf4ed'             # base
  pale: '#908caa'             # subtle

rules:
- description: Progress network device naming convention
  regex: ([a-z]{3}-[0-9,a-z]{2,3}-[a-z]{1}-[a-z]{1}-[a-z]{2}-[0-9,a-z,A-Z]{4})
  color: 
    0: f.red
    1: bold


- description: URL
  regex: |
    (?ix)\b
        ((htt|ft|lda)ps?|telnet|ssh)://  # Scheme
        ([-%:\w\\/]{1,256}@)?  # User info
        [-\w]{1,63}(\.[-\w]{1,63}){0,126}(:\d{1,5})?  # Host and port
        (/[-+=~@%&?#.:;,\w\\/()]*)?  # Path, query, and fragment
    ((?=[.:;,)])|\b)  # Avoid highlighting trailing path characters by matching them in a lookahead
  color: 
    0: b.pale
  exclusive: false

- description: IPv4
  regex: \b(?<!\.)((25[0-5]|(2[0-4]|[0-1]?\d)?\d)\.){3}(25[0-5]|(2[0-4]|[0-1]?\d)?\d)(/\d+)?\b
  color: f.pink
  exclusive: false

- description: IPv6
  regex: |
    (?ix)(?<![\w:])(
        ([\da-f]{1,4}:){7}[\da-f]{1,4}|  # 1:2:3:4:5:6:7:8
        [\da-f]{1,4}:(:[\da-f]{1,4}){1,6}|  # 1::3:4:5:6:7:8
        ([\da-f]{1,4}:){1,2}(:[\da-f]{1,4}){1,5}|  # 1:2::4:5:6:7:8
        ([\da-f]{1,4}:){1,3}(:[\da-f]{1,4}){1,4}|  # 1:2:3::5:6:7:8
        ([\da-f]{1,4}:){1,4}(:[\da-f]{1,4}){1,3}|  # 1:2:3:4::6:7:8
        ([\da-f]{1,4}:){1,5}(:[\da-f]{1,4}){1,2}|  # 1:2:3:4:5::7:8
        ([\da-f]{1,4}:){1,6}:[\da-f]{1,4}|  # 1:2:3:4:5:6::8
        ([\da-f]{1,4}:){1,7}:|  # 1:2:3:4:5:6:7::
        :((:[\da-f]{1,4}){1,7}|:)  # ::2:3:4:5:6:7:8
    )(:(?=\W))?  # \W is an exclusive-flag hack to color the : before an IPv4-embedded address
    (%[\da-z]+)?  # Zone index
    (/\d+)?  # Prefix length
    (?!:?\w)
  color: f.pink
  exclusive: false

- description: MAC address
  regex: |
    (?ix)\b(
        (?<!:)([\da-f]{1,2}:){5}[\da-f]{1,2}(?!:)|  # 11:22:33:aa:bb:cc
        (?<!\.)([\da-f]{4}\.){2}[\da-f]{4}(?!\.)  # 1122.33aa.bbcc
    )\b
  color: f.pink
  exclusive: false

- description: Date
  regex: |
    (?ix)\b(
        (\d{2}|\d{4})(?P<sep1>[-\/\s+])(0?[1-9]|1[0-2])(?P=sep1)(3[0-1]|[1-2]\d|0?[1-9])|  # YYYY-MM-DD, YY-MM-DD, YYYY/MM/DD, YY/MM/DD
        (3[0-1]|[1-2]\d|0?[1-9])(?P<sep2>[-\/])(0?[1-9]|1[0-2])(?P=sep2)(\d{2}|\d{4})|  # DD-MM-YYYY, DD-MM-YY, DD/MM/YYYY, DD/MM/YY
        (0?[1-9]|1[0-2])(?P<sep3>[-\/])(3[0-1]|[1-2]\d|0?[1-9])(?P=sep3)(\d{2}|\d{4})|  # MM-DD-YYYY, MM-DD-YY, MM/DD/YYYY, MM/DD/YY
        (jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+(  # MMM
            (3[0-1]|[1-2]\d|0?[1-9])(\s+\d{4})?|\d{4}  # DD (YYYY)?, YYYY
        )|(3[0-1]|[1-2]\d|0?[1-9])\s(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)(?!\s+(3[0-1]|[1-2]\d|0?[1-9])([^\w:]|$))(\s+\d{4})?  # DD MMM (YYYY)?
    )((?=[\WT_])|$)
  color: f.violet
  exclusive: false

- description: Time
  regex: |
    (?ix)(?<![\.:])(\b|(?<=T))
        (2[0-3]|[0-1]\d):[0-5]\d  # Hours and minutes
        (:[0-5]\d([\.,]\d{3,6})?)?  # (Seconds (sub-seconds, 3 to 6 decimal places)?)?
        ([\-\+](\d{2}|\d{4})|Z)?  # (Timezone)?
    (?![\.:])\b
  color: f.violet
  exclusive: false

- description: Size, like 123G 123Gb 123Gib 1.23G 123Gbps
  regex: (?i)\b\d+(\.\d+)?\s?((([KMGTPEZY](i?B)?)|B)(ps)?)\b
  color:
    0: f.pink
    2: bold
  exclusive: false

- description: Cisco config mode prompt
  regex: ((\(config.*\))?#|@)
  color: 
    0: f.red
    1: bold
  exclusive: false

- description: Protocols
  regex: (^|\s)(ip(v4|v6)?|tcp|udp|esp|ospf|eigrp|bgp|icmp|ftp|http|https|scp|pim|hsrp|vrrp|ssh|www|dhcp|arp(a)?|ike(v1|v2)?|isakmp|pfs)($|\s)
  color: 
    0: f.violet
    2: bold 
  exclusive: false

- description: Cisco keywords
  regex: (^|\s)(description|(passive-)?interface|aaa (authentication|authorization|accounting|session-id|new-model)?|mac address|subnet|storm-control|spanning-tree|cdp|load-interval|(tunnel-|default-|(authentication-|authorization-|accounting-)?server-)?group(-policy|-url)?|vpn(-access-hours)?(-simultaneous-logins)?((-idle|-session)-timeout|(-filter)?)(-tunnel-protocol)?|split(-dns|-tunnel(-policy|-network-list|-all-dns)?)|tacacs(\+|-server)?)($|\s)
  color: 
    0: f.violet
    2: bold
  exclusive: false

- description: Cisco switching keywords
  regex: (^|\s)(switchport( mode)?|
                channel-group|
                (policy-|class-)map|
                udld)($|\s)
  color: 
    0: f.violet
    2: bold
  exclusive: false

- description: Cisco routing keywords
  regex: (^|\s)((auto-)?summary(-only)?|
                (exit-|aggregate)?address(-family|-pool)?|
                (ip\s+|static-)?route(r(-id)?)?(-map)?|
                area|
                auto-cost|
                log-adjacency-changes|
                neighbor|
                network|
                peer(-group)?|
                prefix(-list)?|
                redistribute|
                reference-bandwidth|
                remote-as|
                soft-reconfiguration|
                timers|
                vrf)($|\s)
  color: 
    0: f.violet
    2: bold
  exclusive: false

- description: Cisco Nexus keywords
  regex: (^|\s)(vpc (peer-link)?|
                feature)($|\s)
  color: 
    0: f.violet
    2: bold
  exclusive: false

- description: Cisco ASA keywords
  regex: (^|\s)(failover(( lan (unit|interface)| link?)?)?|( polltime| replication)?|
                fqdn v4|
                access-(list|group)?|
                (network-|service-|group-)?object(-group)?)($|\s)
  color: 
    0: f.violet
    2: bold
  exclusive: false

- description: Cisco firewall failover status in prompt
  regex: (\/(pri|sec)\/(act|stby))
  color:
    0: f.pink
    1: bold

- description: Cisco interface
  regex: (?i)((vlan|
               tunnel|
               po(rt(-)?channel)?|
               lo(opback)?|
               m(ana)?g(e)?m(en)?t|
               (fast| (ten)?gigabit)?eth(ernet)?|
               te|
               gi|
               wan|
               lan)[0-9\/\.]{1,10})
  color: 
    0: f.violet
    1: bold

- description: Cisco logs
  regex: (?i)(%[a-z,A-Z,\-,_,0-9,:]+)
  color: f.violet
  exclusive: true

- description: Cisco configuration values
  regex: (?i)\b(?<=ip ospf priority )\d{1,3}|
               (?<=route-map )[a-z0-9\-]+|
               (?<=prefix-list )[a-z0-9\-]+|
               (?<=router bgp )\d+|
               (?<=router ospf )\d+|
               (?<=router eigrp )\d+|
               (?<=remote-as )\d+|
               (?<=description ).*|
               (?<=fqdn v4 )[a-zA-Z0-9\.\-\_]+|
               (?<=switchport access vlan )\d+|
               (?<=switchport mode )(trunk|access)|
               (?<=access-list )[a-z0-9_\-]+|
               (?<=access-group )[a-z0-9_\-]+|
               (?<=object )[a-z0-9_\-.]+|
               (?<=object-group )[a-z0-9_\-]+|
               (?<=group-policy )[a-z0-9_\-\.]+|
               (?<=tunnel-group )[a-z0-9_\-]+|
               (?<=crypto map )[a-z0-9_\-\.]+|
               (?<=vpn-filter value )[a-zA-Z0-9_\-]+|
               (?<=route )[a-z0-9_\-]+|
               (?<=feature )[a-z0-9_\-\+]+|
               (?<=failover lan unit )[a-zA-Z]+|
               (?<=failover interface ip )[a-zA-Z]+|
               (?<=failover link )[a-zA-Z]+\b
  color: f.pink
  exclusive: false

- description: Cisco - Bad
  regex: (?i)\b(shutdown|incomplete)\b
  color: f.red

- description: Generic - Bad
  regex: (?i)\b(password|abnormal(ly)?|(administratively )?down|los(t|ing)|err(ors?)?|(den(y|ies|ied)?)|reject(ing|ed)?|drop(ped|s)?|(err\-)?disabled?|(timed?\-?out)|fail(s|ed|iure)?|disconnect(ed)?|unreachable|invalid|bad|notconnect|unusable|blk|inaccessible|wrong|collisions?|unsynchronized|mismatch|runts)\b
  color: f.red

- description: Generic - Ambigious bad
  regex: (^|\s)(no(pe)?|exit(ed)?|reset(t?ing)?|discard(ed|ing)?|block(ed|ing)?|filter(ed|ing)?|stop(p(ed|ing))?|never|bad)($|\s)
  color: f.yellow

- description: Cisco - Ambigious bad
  regex: (?i)\b(unassigned)\b
  color: f.yellow

- description: Generic - Not too bad
  regex: (?i)\b(warnings?)\b
  color: f.yellow

- description: Generic - Ambigious good
  regex: (?i)\b(ye(s|ah?|p)?|start(ed|ing)?|running|good|any)\b
  color: f.blue

- description: Cisco - Good
  regex: (^|\s)((protocol-|link-|admin-)?up|(no shutdown))($|\s)
  color: f.blue
  exclusive: false

- description: Generic - Good
  regex: (?i)\b((protocol-|link-|admin-)?up|ok(ay)?|permit(ed|s)?|accept(s|ed)?|enabled?|online|succe((ss(ful|fully)?)|ed(ed)?)?|connect(ed)?|reachable|valid|forwarding|synchronized)\b
  color: f.blue
