k9s:
  cluster: val-test-haas
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
  view:
    active: context
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
