live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
position = "None"
decorations = "Buttonless"
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.85
blur = true
title = "Alacritty"
dynamic_title = false

[window.padding]
x = 10
y = 10

[scrolling]
history = 100000
multiplier = 3

[font]
size = 17.5
builtin_box_drawing = true

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Regular Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 1
y = 1

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "0xfaf4ed"
foreground = "0x575279"

[colors.cursor]
cursor = "0x6e6a86"
text = "0xfaf4ed"

[colors.vi_mode_cursor]
cursor = "0xcecacd"
text = "0x575279"

[colors.normal]
black = "0xf2e9e1"
blue = "0x56949f"
cyan = "0xd7827e"
green = "0x286983"
magenta = "0x907aa9"
red = "0xb4637a"
white = "0x575279"
yellow = "0xea9d34"

[colors.bright]
black = "0x9893a5"
blue = "0x56949f"
cyan = "0xd7827e"
green = "0x286983"
magenta = "0x907aa9"
red = "0xb4637a"
white = "0x575279"
yellow = "0xea9d34"

[colors.hints.end]
background = "#fffaf3"
foreground = "#9893a5"

[colors.hints.start]
background = "#fffaf3"
foreground = "#797593"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "0xdfdad9"
text = "0x575279"

[cursor]
unfocused_hollow = true
thickness = 0.20

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = true

[[hints.enabled]]
action = "copy"
post_processing = false
regex = '([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})|([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})|([0-9A-Fa-f]{4}[.-]){2}([0-9A-Fa-f]{4})'

[hints.enabled.binding]
key = "A"
mods = "Control|Shift"

[[hints.enabled]]
action = "copy"
post_processing = false
regex = "((mar|mro|mor|sof|rot|hyd|atl|msn|bur|lmk|brn|blr)-(hq|ro|3dc|dc|rd)-(c|d|a|e|s)-(d|z|i|w|v|u|s|m|f|t)-(sw|wc|rt|fw|lb|op|ap|ip|sd)-[0-9,a-z,A-Z]{4})"

[hints.enabled.binding]
key = "H"
mods = "Control|Shift"

[[hints.enabled]]
command = "open"
hyperlinks = true
persist = false
post_processing = true
regex ="(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"

